# Site settings
title: The Ruby Mug, LLC
email: rogelio@therubymug.com
description: I'm a humanoid programmer.
baseurl: ""
url: "http://blog.therubymug.com"
twitter_username: therubymug
github_username:  therubymug

# Build settings
markdown: kramdown
